Test_task
Ruslan-Skira/codeit_test_task pull request #2
Opened 2020-08-05 09:35 UTC by Ruslan-Skira

- added classes to the admin part

2020-08-06 15:33 UTC, FerumFlex commented on wingtel/att_subscriptions/admin.py
> +admin.site.register(ATTSubscription)
тут и ниже не плохо бы создать классы для отображения этих данных в админке. (такое уже есть чуть дальше)

2020-08-06 15:35 UTC, FerumFlex commented on wingtel/usage/admin.py
> +    list_display = ('__str__', 'id', 'price', 'usage_date', 'kilobytes_used')
а что выводит тут __str__? если как обычно имя класса и адрес в памяти, то мне кажется это не нужно. Просто можно удалить __str__. (далее к другим класса тоже)

2020-08-06 15:37 UTC, FerumFlex commented on wingtel/usage/serializers.py
> +def price_above_zero(price):
здесь не критично, но можно перенести эту функцию в файл validators.py

2020-08-06 15:39 UTC, FerumFlex commented on wingtel/usage/serializers.py
> +    limit_excess = serializers.IntegerField(validators=[price_above_zero])
можно этот валидатор заменить на параметр min_value
https://www.django-rest-framework.org/api-guide/fields/#integerfield

2020-08-06 15:41 UTC, FerumFlex commented on wingtel/usage/serializers.py
> +                  'price', 'limit_excess')
чуть чуть больше pep8)) между двумя классами должно быть 2 строки. Можно использовать автоформатеры например при коммите оно будет форматировать измененные файлы. https://pre-commit.com/

2020-08-06 15:46 UTC, FerumFlex commented on wingtel/usage/views.py
> +            usage_type = request.GET['type'].lower()
тут возможна необработанная ошибка когда type не определен. то будет 500.

2020-08-06 15:47 UTC, FerumFlex commented on wingtel/usage/views.py
> +            return JsonResponse(serializer.errors, status=400)
если я не ошибаюсь то здесь вылезет ошибка, если usage_type не voice, data. так как serializer не определен.

2020-08-06 15:49 UTC, FerumFlex commented on wingtel/usage/views.py
> +class InvalidPriceKeyError(APIException):
классы ошибок лучше вынести в модуль exceptions

2020-08-06 15:50 UTC, FerumFlex commented on wingtel/usage/tests.py
> +    def test_price_limit(self):
слишком мало тестов ...

2020-08-07 12:55 UTC, Ruslan-Skira commented on wingtel/usage/admin.py
> +    list_display = ('__str__', 'id', 'price', 'usage_date', 'kilobytes_used')
Ok да выводит, что ты сказал. Удаляю.

2020-08-13 09:33 UTC, Ruslan-Skira commented on wingtel/usage/tests.py
> +    def test_price_limit(self):
Дописал если нет ключей какие райзятся ошибки. 
и разделил их на валидные и не валидные.

2020-08-13 10:11 UTC, Ruslan-Skira commented on wingtel/usage/serializers.py
> +                  'price', 'limit_excess')
Наверное во вложенных классах  разделитель только одна пустая строка. 
Pylint редактирует так.

2020-08-20 05:17 UTC, FerumFlex requested changes

2020-08-20 05:17 UTC, FerumFlex commented on wingtel/usage/views.py
> +            usage_type = request.GET['type'].lower()
по проверка уже лучше, но все таки нет проверки типов данных. можно попрбовать привестиз хотя бы к инту, либо для from_date end_date к datetime и если ошибка то выдывать InvalidFromDateKeyError. если найдешь/знаешь готовый модуль для этого то это даже лучше

2020-10-15 11:58 UTC, merged